language: cpp
script:
- cmake -H. -B_build -DCMAKE_INSTALL_PREFIX=_install -DBUILD_TESTS=ON
- cmake --build _build
- cmake --build _build --target install
- cmake --build _build --target test -- ARGS=--verbose
- cmake -H. -B_build
- cmake --build _build
- cd _build
- cpack -G DEB
- cd ..
addons:
  apt:
    sources:
    - george-edison55-precise-backports
    packages:
    - cmake
    - cmake-data
deploy:
  provider: releases
  api_key:  92b8343847599e3119bfaa5e23a17f1e19876e24
  file:
    -_build/*.deb
  skip_cleanup: true
  on:
    tags: true
