image: Visual Studio 2019
platform: x86
configuration: Release

build_script:
  - cmd: cmake -H. -B_build
  - cmd: cmake --build _build --config Release
  - cmd: cd _build
  - cmd: ls
  - cmd: cpack -G WIX
  - cmd: cd ..

artifacts:
  - path: ./_build/print-0.1.0.0-win64.msi
    name: print.msi
deploy:
  release: $(APPVEYOR_REPO_TAG_NAME)
  description: 'Release description'
  provider: GitHub
  auth_token:
    secure: tZdq4qXRLud/z27+KjHqLP0jpdTdUkrQ1XmSJMbSAnd2KTvjSqLjRlueHzHPhzLe # your encrypted token from GitHub
  artifact: print.msi           # upload all NuGet packages to release assets
  on:
    APPVEYOR_REPO_TAG: true        # deploy on tag push only
